name: Build Docker Image
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.7.0
    # So now you can use Actions' own caching!
#     - name: Cache Docker layers
#       uses: actions/cache@v3
#       with:
#         path: /tmp/.buildx-cache
#         key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
#         restore-keys: |
#           ${{ runner.os }}-buildx-
    - name: Login to DockerHub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # And make it available for builds
    - uses: docker/build-push-action@v4.1.0
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
