name: Prod
on:
  push:
    branches:
      - master


jobs:
    build-and-publish:
        # runs-on: ubuntu-latest
        # steps:
        #   - name: Merge sandbox -> production
        #     uses: devmasx/merge-branch@1.4.0
        #     with:
        #       type: now
        #       from_branch: master
        #       target_branch: master2
        #       github_token: ${{ secrets.GITHUB_TOKEN }}

    # deploy-prod:
        runs-on: 'ubuntu-latest'
        steps:
          - name: Run a multi-line script
            run: |
                  echo TEst



          - name: checkout
            uses: actions/checkout@v4
            with:
              ref: master2

          - name: check
            run: cat create.yml
          

          - name: Create Release
            uses: actions/create-release@v1.1.4
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
            with:
              tag_name: 1.1.4
              release_name: Release 1.1.4
              body: |
                Changes in this Release
                - First Change
                - Second Change
              draft: false
              prerelease: false