name: Prod
on:
  push:
    branches:
      - master


jobs:
    build-and-publish:
        # runs-on: ubuntu-latest
        # steps:
        #   - name: Merge sandbox -> production
        #     uses: devmasx/merge-branch@1.4.0
        #     with:
        #       type: now
        #       from_branch: master
        #       target_branch: master2
        #       github_token: ${{ secrets.GITHUB_TOKEN }}

    # deploy-prod:
        runs-on: 'ubuntu-latest'
        outputs:
          output1: ''
          output2: ${{ steps.get.outputs.TEST }}
        steps:

          - name: checkout
            uses: actions/checkout@v4

          - name: Run a multi-line script
            id: get
            run: |
               echo "TEST=123" >> "$GITHUB_OUTPUT"


    build:
      needs: build-and-publish
      name: Build Image
      uses: faridamrah/test/.github/workflows/random.yml@master
      with:
        TAG_SWARM: ${{ needs.build-and-publish.outputs.output1}}
        TAG_EARN: ${{ needs.build-and-publish.outputs.output2 }}
        # runs-on: ubuntu-latest
        # steps:
        #   - name: Merge sandbox -> production
        #     uses: devmasx/merge-branch@1.4.0
        #     with:
        #       type: now
        #       from_branch: master
        #       target_branch: master2
        #       github_token: ${{ secrets.GITHUB_TOKEN }}



    # GetEnv:
    #   runs-on: 'ubuntu-latest'
    #   needs: build-and-publish
    #   steps:
    #       - uses: actions/checkout@v4
    #       - name: env
    #         uses: ./.github/actions/hello-world-action
    #         with:
    #           test: ${{needs.build-and-publish.outputs.output1}}



          # - name: checkout
          #   uses: actions/checkout@v4
          #   with:
          #     ref: master2

          # - name: check
          #   run: cat create.yml
          

          # - name: Create Release
          #   uses: actions/create-release@v1.1.4
          #   env:
          #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          #   with:
          #     commitish: master2
          #     tag_name: 1.1.5
          #     release_name: Release 1.1.5
          #     body: |
          #       Changes in this Release
          #       - First Change
          #       - Second Change
          #     draft: false
          #     prerelease: false