name: Prod
on:
  push:
    branches:
      - master


jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: everlytic/branch-merge@1.1.2
            with:
              github_token: ${{ github.token }}
              source_ref: ${{ github.ref }}
              target_branch: 'master2'
              commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'

    # deploy-prod:
    #     runs-on: 'ubuntu-latest'
    #     environment: 'prod'
    #     steps:
    #       - name: Run a multi-line script
    #         run: |
    #               echo TEst