name: Generate Random Version

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Generate Random Version
      id: random_version
      run: |
        random_version="v$((RANDOM % 1000)).$((RANDOM % 100)).$((RANDOM % 100))"
        echo "Random Version Label: $random_version"
        echo "RANDOM_VERSION=$random_version" >> $GITHUB_ENV

    - name: Use Random Version
      env: 
        random_version: "${{ env.RANDOM_VERSION }}"
      run: |
        echo "Using Random Version Label: $random_version"
