name: Random Version Workflow

on:
  push:
    branches:
      - master

jobs:
  generate-random-version:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Random Version
        id: random_version
        run: |
          # Generate a random version label (e.g., "v0.0.1")
          random_version="v$((RANDOM % 1000)).$((RANDOM % 10)).$((RANDOM % 10))"
          echo "::set-output name=random_version::$random_version"
          
  deploy-subgraph:
    needs: generate-random-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy Subgraph
        env:
          RANDOM_VERSION: ${{ needs.generate-random-version.outputs.random_version }}
        run: |
          echo "Deploying with Random Version: $RANDOM_VERSION"
          # Use $RANDOM_VERSION in your deployment commands
