name: BuildImage

on:
  workflow_call:
    inputs:
      TAG_SWARM:
        type: string
        required: false
      TAG_EARN:
        type: string
        required: false

jobs:
  build-swarm:
    if: ${{ inputs.TAG_SWARM }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: TEst1
        run:
            echo ${{inputs.TAG_SWARM}}


  build-earn:
    if: ${{ inputs.TAG_EARN }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v4

      - name: TEst2
        run:
            echo ${{inputs.TAG_EARN}}
